server:
  port: 8901
spring:
 datasource:
    url: jdbc:postgresql://localhost:5432/imdb
    username: koud
    password: 12345
    platform: POSTGRESQL
    driverClassName: org.postgresql.Driver
# cloud:
#    config:
#      enabled: false
#      uri: http://localhost:8888
#      fail-fast: false
logging:
  path: authLogs
signing.key: koudKey
